### ISSUE TITLE
下载整个Demo，在IE11还是显示空白，谷歌可以正常显示

### ISSUE THREAD

**Issue by renff** [lanux/Vue-Admin#11] opened 2017-11-16 00:26 UTC
源码下载，安装组件后，在IE11下还显示空白，但谷歌可以正常显示，要做什么配置吗？望帮忙解决下，谢谢！
出错提示：
SCRIPT1003: 缺少 ':'
文件: app.js，行: 40071，列: 69

40071行   /* harmony default export */ __webpack_exports__["default"] = ({ use, t, i18n });

**Comment by lanux** [comment] 2017-11-17 05:46
webpack.base.conf.js 里面有没有下面这段？
{
        test: /\.js$/,
        loader: 'babel-loader',
        //exclude: /(node_modules|bower_components)/,
        // 注意elementUI的源码使用ES6需要解析
        include: [
          resolve('src'),
          resolve('test'),
          resolve('/node_modules/.1.4.8@element-ui/src'),
          resolve('/node_modules/.1.4.8@element-ui/packages'),
          resolve('/node_modules/.4.3.0@vuex-router-sync')
        ]
      },

**Comment by lanux** [comment] 2017-11-17 05:47
@renff

**Comment by lanux** [comment] 2017-11-17 05:58
Duplicate of #10

**Comment by renff** [comment] 2017-11-20 07:24
有这段代码啊
{
        test: /\.js$/,
        loader: 'babel-loader',
        //exclude: /(node_modules|bower_components)/,
        // 注意elementUI的源码使用ES6需要解析
        include: [
          resolve('src'),
          resolve('test'),
          resolve('/node_modules/.1.4.8@element-ui/src'),
          resolve('/node_modules/.1.4.8@element-ui/packages'),
          resolve('/node_modules/.4.3.0@vuex-router-sync')
        ],
        query: {
          presets: ['es2015-loose']
        }
      },

**Comment by lanux** [comment] 2017-11-20 07:45
resolve('/node_modules/.1.4.8@element-ui/src'),
resolve('/node_modules/.1.4.8@element-ui/packages'),
resolve('/node_modules/.4.3.0@vuex-router-sync')

**Comment by lanux** [comment] 2017-11-20 07:45
改成你自己的版本号

**Comment by renff** [comment] 2017-11-20 07:50
下载的你写的Demo没做什么操作，package.json中的是"element-ui": "^1.4.8",呀，而且node_modules\element-ui中的也是"raw": "element-ui@^1.4.8",

**Comment by renff** [comment] 2017-11-21 01:09
作者你好，希望您帮忙看下，我是把你的源码下载直接运行的，在IE11下还是不行，显示空白

**Comment by lanux** [comment] 2017-11-21 07:29
你clone源码 install 之后，项目node_modules目录下面找到对应的element-ui 版本和vuex-router-sync 替换掉webpack.base.conf.js 里面那段配置

**Comment by renff** [comment] 2017-11-21 08:36
"_args": [
    [
      {
        "raw": "element-ui@^1.4.8",
        "scope": null,
        "escapedName": "element-ui",
        "name": "element-ui",
        "rawSpec": "^1.4.8",
        "spec": ">=1.4.8 <2.0.0",
        "type": "range"
      },
      "D:\\App\\Vue-Admin-master"
    ]
  ],
  "_cnpm_publish_time": 1510629028387,
  "_from": "element-ui@>=1.4.8 <2.0.0",
  "_hasShrinkwrap": false,
  "_id": "element-ui@1.4.10",
  "_inCache": true,


[
      {
        "raw": "vuex-router-sync@^4.3.0",
        "scope": null,
        "escapedName": "vuex-router-sync",
        "name": "vuex-router-sync",
        "rawSpec": "^4.3.0",
        "spec": ">=4.3.0 <5.0.0",
        "type": "range"
      },
      "D:\\App\\Vue-Admin-master"
    ]
  ],
  "_cnpm_publish_time": 1505748115918,
  "_from": "vuex-router-sync@>=4.3.0 <5.0.0",
  "_hasShrinkwrap": false,
  "_id": "vuex-router-sync@4.3.2",
  "_inCache": true,


element-ui为1.4.10和vuex-router-sync为4.3.2，可以还不对，具体版号是写哪呀？我对这个不熟悉，真不太懂？求帮助，谢谢

**Comment by renff** [comment] 2017-11-21 09:04
多谢，已经弄出来，谢谢

**Closed** 2017-11-21 09:18 UTC
